Odiseo\Bundle\EleccoBundle\Entity\User:
    type: entity
    table: user
    fields:
        passport:
            column: passport
            type: string
            length: 255
            nullable: true
        birthdate:
            column: birthdate
            type: date
            length: 255
            nullable: true
        videoName:
            column: videoName
            type: string
            length: 255
            nullable: true
        country:
            column: country
            type: string
            length: 255
            nullable: true
        isPaid:
            type: boolean
            nullable: true