services:
    odiseo_branca_rally.media_converter:
        class: Odiseo\Bundle\BrancaRallyBundle\Converter\MediaConverter
        arguments: [@service_container]

    app.services.mail:
        class: Odiseo\Bundle\EleccoBundle\Services\MailService
        arguments: ["@service_container", %email_from% , %email_subject% , %email_name%]

    elecco.form.type.user:
        class: Odiseo\Bundle\EleccoBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: odiseo_elecco_user }