easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    site_name: 'Elecco'
    list_actions: ['edit', 'show']
    entities:
        User:
            label: 'Usuarios'
            class: Odiseo\Bundle\EleccoBundle\Entity\User
            list:
                title: "Usuarios"
                fields: ['id', { property: 'fullname', label: 'Nombre' }, { property: 'passport', label: 'Passport' },'birthdate','country','isPaid' ]
                action_edit: "aa"
            new:
                action_label: "Nuevo usuario"
                fields: [ { property: 'fullname', label: 'Nombre' }, { property: 'passport', label: 'Passport' },'birthdate','country','isPaid' ]
                title:  "Nuevo usuario"
            edit:
                fields: [ { property: 'fullname', label: 'Nombre' }, { property: 'passport', label: 'Passport' },'birthdate','country','isPaid' ]
                title:  'Editar usuario'
            show:
                title: "Mostrando usuario "
                fields: ['id', { property: 'fullname', label: 'Nombre' }, { property: 'passport', label: 'Passport' },'birthdate','country','isPaid' ]