parameters:
    odiseo_project.model.user: Odiseo\Bundle\EleccoBundle\Entity\User
    odiseo_project.repository.user: Odiseo\Bundle\ProjectBundle\Repository\UserRepository
    
    odiseo_backend.homepage_route: odiseo_elecco_backend_dashboard