#Odiseo Backend Routes
odiseo_backend:
    resource: "@OdiseoBackendBundle/Resources/config/routing/main.yml"
    prefix:   /

odiseo_elecco_dashboard:
    pattern: /dashboard
    defaults: { _controller: "OdiseoEleccoBundle:Backend/Main:dashboard" }